name: CreateIssueWorkflow GitHub API
on: [ push ]
    #branches:
    #  - "master"
#You can use the GITHUB_TOKEN to make authenticated API calls. This example workflow creates an issue using the GitHub REST API:
jobs:
  create_issue:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Push Random file 
        run: |
          pwd  # where we are working directory
          ls -a # list files in working directory
          # instead of checkout action we have to clone ourselves in working directory
          git init
          #git remote add origin "clone url passed here"
          #url to authorise with github-token
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          #https://github.com/sureshmusale/Second-LearnGithubActions.git
          git config --global user.email "boss@suresh.com"
          git config --global user.name "boss-suresh"
          git fetch
          git checkout "master"
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m "save random file"
          git push
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail