name: Fail-Check

on: [push]

jobs:
  failcheck-job:
    runs-on: ubuntu-latest
    steps:
      - name: failcheckstep
        run: |
          echo "STep 1" #for sure this step will fail but if you want to run the next step then 
            # you have to add failure() in the step which you need to run at any cost
      - name: Step 2
        #if: failure() 
        run: |
          echo "Step 2"
      - name: Step 3
        run: |
          echo "STep 3"