name: Functions script

on: [ push ]

jobs:
  Functions:
    runs-on: ubuntu-latest
    steps:
      - name: Functions steps
        run: |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startswith( 'hello', 'he' ) }}
          echo ${{ endswith( 'hello', 'o' ) }}
          
