name: Functions

on: [push, pull_request]
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
    - name: Functions Test
      run: |
        echo "This is first step"
  Second-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: First - Step 
        run: |
          echo "this is second job runs only on pull_request"
      - name: Second step
        run: |
          eecho "Second Step executed"
        if: failure() #job status function this will returns true only when the previous step failed
      - name: Third Step
        run: |
          echo "this step is executed due to the Failure() addition"