name: Github actions workflow
on:
  push:
    branches:
      - "master"

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Step name
        run: |
          echo " you should see this in only development branch only"