name: Log Node version

on: push

jobs:
  Matrix:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:    # for this action input will be given by with command
          node-version: 6
      - name: log node version again
        run: node -v
        